---
apiVersion: v2
type: application
appVersion: "1.1.0"
description: A Helm chart to deploy the Anexia CloudDNS cert-manager ACME solver webhook
name: cert-manager-webhook-anexia
version: 1.0.6
maintainers: []
