name: Lint Helm Charts

on: [pull_request, push]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Helm
        uses: azure/setup-helm@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.7.0

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --chart-dirs deploy --remote origin --target-branch main)
          if [[ -n "$changed" ]]; then
            echo "name=changed" >> $GITHUB_OUTPUT
          fi

      - name: Run chart-testing (lint)
        run: ct lint --chart-dirs deploy --remote origin --target-branch main
