on:
  push:
    branches:
      - main
  pull_request:

name: Integration tests

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-go@v4
      with:
        go-version: 'stable'
        cache: true

    - name: Insert required Anexia token into secret
      run: sed -i 's/changemeplease/${{ secrets.ANEXIA_CLOUDDNS_TOKEN }}/g' testdata/anexia/anexia-clouddns-secret.yml

    - name: Set reusable test zone name environment variable
      run: echo "TEST_ZONE_NAME=cert-manager-anexia-webhook-tests.test." >> $GITHUB_ENV

    - name: Assemble test FQDN from commit SHA and test zone
      run: echo "TEST_FQDN=$GITHUB_SHA.$TEST_ZONE_NAME" >> $GITHUB_ENV

    - name: Run integration tests
      run: echo "Running tests against $TEST_FQDN" && make test
